### ISSUE TITLE
How To Make Top Tabs RNN2

### ISSUE THREAD

**Issue by zaycode** [codebymani/React-Native-Starter-RNN2#1]
How To Make Top Tabs RNN2
more question: https://github.com/wix/react-native-navigation/issues/4357

**Comment by smooJitter** [comment]
Here for the comments

**Comment by codebymani** [comment]
@nusantaraid @smooJitter sorry for the late response. I've been through the react native navigation docs and not able to find appropriate reference. V2 is still under development and unstable, so better use https://github.com/skv-headless/react-native-scrollable-tab-view for the nested tabs.
